apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mp-test1-secret
  namespace: default
spec:
  encryptedData:
    secret: AgBTOC49Nv1qc79IQYwU9POALHKhojIrRugXTqqMwZtjphBe5S9JrRUC8vHyukdgi9RHBWmjq2CL68qXe8J594MNz6SlHi38BYZjkEuqKA8+8Cu0jCKZ0ULSa2j8afsuKAxND+q1Qj2xALrEcQ/XvMI+cp7qJQHoB3vE11EMRtkhEDXjmF3ogcODPZAgy7TzvjEHJ/pfoGKAlV1BkU+A3SefCRF4Tdih1goElwT2LHeB6JNM/M+BBsg/Y3uZrPU0mytoqbn4op6Yk/7+H0VZfrV2W+BK1R9EZZn4IwnXczRsjSxUD5MQA4udiNkHpCQD0ynEdhWEVULWhYNAxzKjct8sTTYbUdC5U45pu6XVtZ6fqlqfmBwMJwHM0os2TGDyM7BA3eooCyFfEHyjKiOvuOxgdsdq+W+WIYeOctqEwYBnbopQTXdrPlLUKpfPZQIkqF5qeVQ/dbRwGQJpzYkB8zVrucgM0BwhntPp6xFPNy/jICDawEKnhja7cs/Qw74ccXnXYkoNE/SRB0puUchNdGttAq9pRLg7iVkTM6q9OlNtvguDBuB17hMHh04XexOz67cLnMUV/nnngGvCMz8WU+wuC4lHoPlERfHdZD9qXyBpIgQcTAyfzJgmH+Ki6eMnWzYojHGEhzv55Soai3Y9FBU3k6vdcrUlUiuDa9CUc7H2LTqVecRXG29/09Doi6zMFeqKc+w=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mp-test1-secret
      namespace: default

