apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mp-test2-secret
  namespace: default
spec:
  encryptedData:
    secret: AgA2RM8CXCc5tXOgfufli8AfPXdOfm9ULtCAvh67+EJslOYIBAv5QrcitW1slM9GqjzUC8sV1+n2Zf++7rw38CHCrl1BruySAR8SjzyOJw0sgZsVxUbJ1aS8m+uyDNxdrXS9UjpVUjPRy06PgVRTnZ10rM77i2E6V+3/Q2PApo9vw6dXE2qZ6mxLezqSDoXXSB1KKAVma9L4jCVPpXqmmN5jjnXwR3DQVYXVCjBAtLmoiWw1YiQaHOH4XvgMWqjmVWyQb7nQdXa+nEwiKD7hP7Z6TQMbP2K5R2xUKPcxgVAMgqlHbO7dsK4EEmQTGYR6E3kWYLvswkrc8PDH+VNKoF3d3n2SF/G2ikcbY9aJgjluIZL6P+BywBYOF9zVWbgM1VeLWq0rwjriTNJ2+P19b9aHmgca6J8VwJJDWKJMmtiUiBhsBvunIduCWrsM0bItEW6670866DReQY+xvg72mOTVmbYfnGwoLSlkMP2qVFVcuPNhp+JnD3qfEZzjrN1RyiOJROqOpeJdIBDdt4KCswXS7M83nYNtXzs4YeXKOwhw21tcgBLBrqomfBheTplRv3akj4ONIP0KP4akCvMo+o3OvNOe2kQ5t2ShTb/9NK328hZ+mmzHkCEPIR1Wfx66eiCuIYowOLcya3iv7xwD13giOIzQQpHP+DzVv7OnkCMuxS0tAt94DQzY1c7kjZnJEIWVYCI=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mp-test2-secret
      namespace: default

